/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResidencesRouteImport } from './routes/residences'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidenceIdRouteImport } from './routes/residence.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencesRoute = ResidencesRouteImport.update({
  id: '/residences',
  path: '/residences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidenceIdRoute = ResidenceIdRouteImport.update({
  id: '/residence/$id',
  path: '/residence/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/residences': typeof ResidencesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/residence/$id': typeof ResidenceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/residences': typeof ResidencesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/residence/$id': typeof ResidenceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/residences': typeof ResidencesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/residence/$id': typeof ResidenceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/residences' | '/sitemap.xml' | '/residence/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/residences' | '/sitemap.xml' | '/residence/$id'
  id: '__root__' | '/' | '/residences' | '/sitemap.xml' | '/residence/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResidencesRoute: typeof ResidencesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ResidenceIdRoute: typeof ResidenceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residences': {
      id: '/residences'
      path: '/residences'
      fullPath: '/residences'
      preLoaderRoute: typeof ResidencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residence/$id': {
      id: '/residence/$id'
      path: '/residence/$id'
      fullPath: '/residence/$id'
      preLoaderRoute: typeof ResidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResidencesRoute: ResidencesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ResidenceIdRoute: ResidenceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
